### ISSUE TITLE
[APP REQUEST]: Firefly iii

### ISSUE THREAD

**Issue by limitlessbritt** [SelfhostedPro/selfhosted_templates#154] opened 2020-06-21 20:18 UTC
### Dockerhub Link: ###
https://hub.docker.com/r/jc5x/firefly-iii

### Description ###
"Firefly III" is a (self-hosted) manager for your personal finances. It can help you keep track of your expenses and income, so you can spend less and save more. Firefly III supports the use of budgets, categories and tags. It can import data from external sources and it has many neat financial reports available.

Firefly III should give you insight into and control over your finances. Money should be useful, not scary. You should be able to see where it is going, to feel your expenses and to... wow, I'm going overboard with this aren't I?

But you get the idea: this is your money. These are your expenses. Stop them from controlling you. I built this tool because I started to dislike money. Having money, not having money, paying bills with money, you get the idea. But no more. I want to feel "safe", whatever my balance is. And I hope this tool can help you. I know it helps me.

### Separate Database? ###
MySQL

**Comment by SelfhostedPro** [comment] 2020-06-22 04:50
Duplicate of https://github.com/SelfhostedPro/selfhosted_templates/issues/104

**Closed by SelfhostedPro** 2020-06-22 04:50 UTC
Labels: App Request
