### ISSUE TITLE
Please create new config file for arm devices

### ISSUE THREAD

**Issue by orhanar** [SelfhostedPro/selfhosted_templates#195] opened 2020-10-10 17:21 UTC
Some services does not work on arm devices like pi. Please create different config file that is tested on such devices so we know it works on devices like Pi. Thanks.

**Comment by pingywon** [comment] 2020-10-28 12:31
Been working on one here:
https://github.com/SelfhostedPro/selfhosted_templates/tree/pingywon-yacht-arm

All these apps have been tested with a Raspberry Pi 4. The docker image was either changed for ARM or if no arm version existed the app was removed. 

Waiting on some formatting changes but then you will be able to just load the ARM template.

I always looking for more ARM apps to add too btw.

**Comment by orhanarifoglu** [comment] 2020-11-15 12:10
> Been working on one here:
> 
> https://github.com/SelfhostedPro/selfhosted_templates/tree/pingywon-yacht-arm
> 
> 
> 
> All these apps have been tested with a Raspberry Pi 4. The docker image was either changed for ARM or if no arm version existed the app was removed. 
> 
> 
> 
> Waiting on some formatting changes but then you will be able to just load the ARM template.
> 
> 
> 
> I always looking for more ARM apps to add too btw.

I'll check this out, thanks.

**Comment by orhanarifoglu** [comment] 2020-11-28 17:50
> Been working on one here:
> https://github.com/SelfhostedPro/selfhosted_templates/tree/pingywon-yacht-arm
> 
> All these apps have been tested with a Raspberry Pi 4. The docker image was either changed for ARM or if no arm version existed the app was removed.
> 
> Waiting on some formatting changes but then you will be able to just load the ARM template.
> 
> I always looking for more ARM apps to add too btw.

Hi coudnt find your email. When is this gone be available you reckon? I imported the list but nothing is getting displayed so i guess it hasnt been verified yet?

**Comment by pingywon** [comment] 2020-11-30 11:56
Hey sorry! I thought this was all resolved. @SelfhostedPro can you help?

**Comment by kylo252** [comment] 2021-03-07 13:01
I just tested the Arm template and all I can see is the last entry, that would be SWAG in this case: 

<img src="https://user-images.githubusercontent.com/59826753/110238773-bddf5a80-7f43-11eb-8f16-ac115c812b08.png" width="350" height="460">

You can see it here: 
https://github.com/SelfhostedPro/selfhosted_templates/blob/412780d44b71e821314b864739f92508488eeb1e/Template/template.yml#L2158-L2160

I then tested using a modified [template](https://gist.githubusercontent.com/kylo252/620f62e267b3a4a93a3a0da587ffee91/raw/c9bb93bf50f55b9aff2bf14b2a6ff1815fec715b/template.yml) with SWAG removed, and sure enough it's only Papermerge now showing up. 

<img src="https://user-images.githubusercontent.com/59826753/110238720-7789fb80-7f43-11eb-8094-fe2234a0d2a7.png" width="350" height="460">

---
I can see that https://github.com/SelfhostedPro/Yacht/pull/75 has been merged for a while now, but something must've mocked it up. From a quick glance over the code, I think that the problem is here: 

https://github.com/SelfhostedPro/Yacht/blob/master/backend/api/db/crud/templates.py#L56

I think we should be using `yaml.load_all()` instead as per the [docs](https://pyyaml.org/wiki/PyYAMLDocumentation)
> If a string or a file contains several documents, you may load them all with the yaml.load_all function.

I can't test the code unfortunately since I'm having issues with `mysql_config` dependecies on both my Linux and Win10 machines. It might be somethig simple tho since my experience with Python is pretty limited. 


@SelfhostedPro, Let me know if you require more info. Hopefully this has been helpful to someone :)

**Comment by SelfhostedPro** [comment] 2021-03-07 14:25
yaml.load_all() is unsafe which is why I'm using the safeload. The correct arm branch to use is this one:
https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/yacht-arm/Template/template.yml

As the one you're trying has errors and is not valid yaml.

**Comment by kylo252** [comment] 2021-03-07 14:56
Thank you! It's indeed working correctly. 

---

> The correct arm branch to use is this one:
> https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/yacht-arm/Template/template.yml

I think it might be a good idea to point it out in the README somewhere. And on a related note, maybe link the new https://yacht.sh/docs/ in Yacht's repo description :)

**Comment by SelfhostedPro** [comment] 2021-03-07 14:59
I'll definitely add the info there. I'm looking at changing around how the repo is laid out so there may be a different URL that's recommended in the future. I'll make sure whatever I wind up doing, that it's in the documentation.

**Closed by SelfhostedPro** 2021-03-07 14:59 UTC
